package com.macro.mall.mapper;

import com.macro.mall.model.BatchOrder;
import com.macro.mall.model.BatchOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BatchOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_order
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    long countByExample(BatchOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_order
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int deleteByExample(BatchOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_order
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int deleteByPrimaryKey(Long batchOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_order
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int insert(BatchOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_order
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int insertSelective(BatchOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_order
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    List<BatchOrder> selectByExample(BatchOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_order
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    BatchOrder selectByPrimaryKey(Long batchOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_order
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByExampleSelective(@Param("row") BatchOrder row, @Param("example") BatchOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_order
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByExample(@Param("row") BatchOrder row, @Param("example") BatchOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_order
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByPrimaryKeySelective(BatchOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table batch_order
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByPrimaryKey(BatchOrder row);
}