package com.macro.mall.mapper;

import com.macro.mall.model.CartItem;
import com.macro.mall.model.CartItemExample;
import com.macro.mall.model.CartItemKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CartItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    long countByExample(CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int deleteByExample(CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int deleteByPrimaryKey(CartItemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int insert(CartItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int insertSelective(CartItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    List<CartItem> selectByExample(CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    CartItem selectByPrimaryKey(CartItemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByExampleSelective(@Param("row") CartItem row, @Param("example") CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByExample(@Param("row") CartItem row, @Param("example") CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByPrimaryKeySelective(CartItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByPrimaryKey(CartItem row);
}