package com.macro.mall.mapper;

import com.macro.mall.model.Category;
import com.macro.mall.model.CategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    long countByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int deleteByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int deleteByPrimaryKey(Long categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int insert(Category row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int insertSelective(Category row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    List<Category> selectByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    Category selectByPrimaryKey(Long categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByExampleSelective(@Param("row") Category row, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByExample(@Param("row") Category row, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByPrimaryKeySelective(Category row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByPrimaryKey(Category row);
}