package com.macro.mall.mapper;

import com.macro.mall.model.Merchant;
import com.macro.mall.model.MerchantExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MerchantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    long countByExample(MerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int deleteByExample(MerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int deleteByPrimaryKey(Long merchantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int insert(Merchant row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int insertSelective(Merchant row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    List<Merchant> selectByExample(MerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    Merchant selectByPrimaryKey(Long merchantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByExampleSelective(@Param("row") Merchant row, @Param("example") MerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByExample(@Param("row") Merchant row, @Param("example") MerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByPrimaryKeySelective(Merchant row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByPrimaryKey(Merchant row);
}