package com.macro.mall.mapper;

import com.macro.mall.model.OrderItem;
import com.macro.mall.model.OrderItemExample;
import com.macro.mall.model.OrderItemKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    long countByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int deleteByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int deleteByPrimaryKey(OrderItemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int insert(OrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int insertSelective(OrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    List<OrderItem> selectByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    OrderItem selectByPrimaryKey(OrderItemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByExampleSelective(@Param("row") OrderItem row, @Param("example") OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByExample(@Param("row") OrderItem row, @Param("example") OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByPrimaryKeySelective(OrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByPrimaryKey(OrderItem row);
}