package com.macro.mall.mapper;

import com.macro.mall.model.Product;
import com.macro.mall.model.ProductExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    long countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int deleteByPrimaryKey(Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int insert(Product row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int insertSelective(Product row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    List<Product> selectByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    Product selectByPrimaryKey(Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByExampleSelective(@Param("row") Product row, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByExample(@Param("row") Product row, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByPrimaryKeySelective(Product row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sat Dec 27 23:03:59 CST 2025
     */
    int updateByPrimaryKey(Product row);

    /**
     * 查询指定分类下最新创建的商品（带销量和最低价格）
     *
     * @param categoryId 分类ID
     * @param limit 限制数量
     * @return 商品列表（Map格式）
     */
    List<Map<String, Object>> selectLatestByCategory(@Param("categoryId") Long categoryId, @Param("limit") int limit);

    /**
     * 查询全站销量Top N的商品
     *
     * @param limit 限制数量
     * @return 商品列表（Map格式）
     */
    List<Map<String, Object>> selectTopSales(@Param("limit") int limit);

    /**
     * 分页查询分类下的商品（按创建时间倒序）
     * 支持单个或多个分类筛选
     *
     * @param categoryIds 分类ID列表（可为null或空，表示查询所有商品）
     * @param offset 偏移量
     * @param limit 限制数量
     * @return 商品列表（Map格式）
     */
    List<Map<String, Object>> selectByCategoriesWithPaging(@Param("categoryIds") List<Long> categoryIds, @Param("offset") int offset, @Param("limit") Integer limit);

    /**
     * 统计分类下的商品总数
     * 支持单个或多个分类筛选
     *
     * @param categoryIds 分类ID列表（可为null或空，表示统计所有商品）
     * @return 商品总数
     */
    Long countByCategories(@Param("categoryIds") List<Long> categoryIds);

    /**
     * 查询商品销量
     *
     * @param productId 商品ID
     * @return 销量
     */
    Integer getProductSales(@Param("productId") Long productId);

    /**
     * 分页查询店铺下的商品（支持筛选）
     *
     * @param shopId 店铺ID
     * @param status 商品状态（可选，null表示查询所有状态）
     * @param categoryIds 分类ID列表（可选，null或空表示查询所有分类）
     * @param offset 偏移量
     * @param limit 限制数量
     * @return 商品列表（Map格式，包含商品信息和最低价格、销量、分类ID）
     */
    List<Map<String, Object>> selectByShopIdWithPaging(
            @Param("shopId") Long shopId,
            @Param("status") Integer status,
            @Param("categoryIds") List<Long> categoryIds,
            @Param("offset") int offset,
            @Param("limit") Integer limit
    );

    /**
     * 统计店铺下的商品总数（支持筛选）
     *
     * @param shopId 店铺ID
     * @param status 商品状态（可选，null表示统计所有状态）
     * @param categoryIds 分类ID列表（可选，null或空表示统计所有分类）
     * @return 商品总数
     */
    Long countByShopId(@Param("shopId") Long shopId, @Param("status") Integer status, @Param("categoryIds") List<Long> categoryIds);
}