/* tslint:disable */
/* eslint-disable */
/**
 * TheMall Admin API 文档
 * TheMall 商城管理系统 API 接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@themall.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CommonResultAuditLogListVO } from '../models';
// @ts-ignore
import type { CommonResultAuditLogVO } from '../models';
/**
 * AdminAuditLogControllerApi - axios parameter creator
 */
export const AdminAuditLogControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} auditId 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuditLogDetail: async (auditId: number, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'auditId' is not null or undefined
            assertParamExists('getAuditLogDetail', 'auditId', auditId)
            const localVarPath = `/api/admin/audit-logs/{auditId}`
                .replace(`{${"auditId"}}`, encodeURIComponent(String(auditId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [targetType] 
         * @param {string} [operationType] 
         * @param {number} [adminUserId] 
         * @param {number} [targetId] 
         * @param {string} [startTime] 
         * @param {string} [endTime] 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuditLogList: async (targetType?: string, operationType?: string, adminUserId?: number, targetId?: number, startTime?: string, endTime?: string, page?: number, size?: number, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/audit-logs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (targetType !== undefined) {
                localVarQueryParameter['targetType'] = targetType;
            }

            if (operationType !== undefined) {
                localVarQueryParameter['operationType'] = operationType;
            }

            if (adminUserId !== undefined) {
                localVarQueryParameter['adminUserId'] = adminUserId;
            }

            if (targetId !== undefined) {
                localVarQueryParameter['targetId'] = targetId;
            }

            if (startTime !== undefined) {
                localVarQueryParameter['startTime'] = (startTime as any instanceof Date) ?
                    (startTime as any).toISOString() :
                    startTime;
            }

            if (endTime !== undefined) {
                localVarQueryParameter['endTime'] = (endTime as any instanceof Date) ?
                    (endTime as any).toISOString() :
                    endTime;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminAuditLogControllerApi - functional programming interface
 */
export const AdminAuditLogControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminAuditLogControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} auditId 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAuditLogDetail(auditId: number, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResultAuditLogVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAuditLogDetail(auditId, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAuditLogControllerApi.getAuditLogDetail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [targetType] 
         * @param {string} [operationType] 
         * @param {number} [adminUserId] 
         * @param {number} [targetId] 
         * @param {string} [startTime] 
         * @param {string} [endTime] 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAuditLogList(targetType?: string, operationType?: string, adminUserId?: number, targetId?: number, startTime?: string, endTime?: string, page?: number, size?: number, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResultAuditLogListVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAuditLogList(targetType, operationType, adminUserId, targetId, startTime, endTime, page, size, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAuditLogControllerApi.getAuditLogList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminAuditLogControllerApi - factory interface
 */
export const AdminAuditLogControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminAuditLogControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {number} auditId 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuditLogDetail(auditId: number, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultAuditLogVO> {
            return localVarFp.getAuditLogDetail(auditId, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [targetType] 
         * @param {string} [operationType] 
         * @param {number} [adminUserId] 
         * @param {number} [targetId] 
         * @param {string} [startTime] 
         * @param {string} [endTime] 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuditLogList(targetType?: string, operationType?: string, adminUserId?: number, targetId?: number, startTime?: string, endTime?: string, page?: number, size?: number, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultAuditLogListVO> {
            return localVarFp.getAuditLogList(targetType, operationType, adminUserId, targetId, startTime, endTime, page, size, authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminAuditLogControllerApi - interface
 */
export interface AdminAuditLogControllerApiInterface {
    /**
     * 
     * @param {number} auditId 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAuditLogDetail(auditId: number, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultAuditLogVO>;

    /**
     * 
     * @param {string} [targetType] 
     * @param {string} [operationType] 
     * @param {number} [adminUserId] 
     * @param {number} [targetId] 
     * @param {string} [startTime] 
     * @param {string} [endTime] 
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAuditLogList(targetType?: string, operationType?: string, adminUserId?: number, targetId?: number, startTime?: string, endTime?: string, page?: number, size?: number, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultAuditLogListVO>;

}

/**
 * AdminAuditLogControllerApi - object-oriented interface
 */
export class AdminAuditLogControllerApi extends BaseAPI implements AdminAuditLogControllerApiInterface {
    /**
     * 
     * @param {number} auditId 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAuditLogDetail(auditId: number, authorization?: string, options?: RawAxiosRequestConfig) {
        return AdminAuditLogControllerApiFp(this.configuration).getAuditLogDetail(auditId, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} [targetType] 
     * @param {string} [operationType] 
     * @param {number} [adminUserId] 
     * @param {number} [targetId] 
     * @param {string} [startTime] 
     * @param {string} [endTime] 
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAuditLogList(targetType?: string, operationType?: string, adminUserId?: number, targetId?: number, startTime?: string, endTime?: string, page?: number, size?: number, authorization?: string, options?: RawAxiosRequestConfig) {
        return AdminAuditLogControllerApiFp(this.configuration).getAuditLogList(targetType, operationType, adminUserId, targetId, startTime, endTime, page, size, authorization, options).then((request) => request(this.axios, this.basePath));
    }
}

