/* tslint:disable */
/* eslint-disable */
/**
 * TheMall Admin API 文档
 * TheMall 商城管理系统 API 接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@themall.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AuditMerchantRequest } from '../models';
// @ts-ignore
import type { CommonResultMerchantVO } from '../models';
// @ts-ignore
import type { CommonResultVoid } from '../models';
// @ts-ignore
import type { UpdateMerchantStatusRequest } from '../models';
/**
 * AdminMerchantControllerApi - axios parameter creator
 */
export const AdminMerchantControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} merchantId 
         * @param {AuditMerchantRequest} auditMerchantRequest 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        auditMerchant: async (merchantId: number, auditMerchantRequest: AuditMerchantRequest, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'merchantId' is not null or undefined
            assertParamExists('auditMerchant', 'merchantId', merchantId)
            // verify required parameter 'auditMerchantRequest' is not null or undefined
            assertParamExists('auditMerchant', 'auditMerchantRequest', auditMerchantRequest)
            const localVarPath = `/api/admin/merchants/{merchantId}/audit`
                .replace(`{${"merchantId"}}`, encodeURIComponent(String(merchantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(auditMerchantRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} merchantId 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMerchantDetail: async (merchantId: number, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'merchantId' is not null or undefined
            assertParamExists('getMerchantDetail', 'merchantId', merchantId)
            const localVarPath = `/api/admin/merchants/{merchantId}`
                .replace(`{${"merchantId"}}`, encodeURIComponent(String(merchantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} merchantId 
         * @param {UpdateMerchantStatusRequest} updateMerchantStatusRequest 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateMerchantStatus: async (merchantId: number, updateMerchantStatusRequest: UpdateMerchantStatusRequest, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'merchantId' is not null or undefined
            assertParamExists('updateMerchantStatus', 'merchantId', merchantId)
            // verify required parameter 'updateMerchantStatusRequest' is not null or undefined
            assertParamExists('updateMerchantStatus', 'updateMerchantStatusRequest', updateMerchantStatusRequest)
            const localVarPath = `/api/admin/merchants/{merchantId}/status`
                .replace(`{${"merchantId"}}`, encodeURIComponent(String(merchantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateMerchantStatusRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminMerchantControllerApi - functional programming interface
 */
export const AdminMerchantControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminMerchantControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} merchantId 
         * @param {AuditMerchantRequest} auditMerchantRequest 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditMerchant(merchantId: number, auditMerchantRequest: AuditMerchantRequest, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResultVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.auditMerchant(merchantId, auditMerchantRequest, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMerchantControllerApi.auditMerchant']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} merchantId 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMerchantDetail(merchantId: number, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResultMerchantVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMerchantDetail(merchantId, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMerchantControllerApi.getMerchantDetail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} merchantId 
         * @param {UpdateMerchantStatusRequest} updateMerchantStatusRequest 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateMerchantStatus(merchantId: number, updateMerchantStatusRequest: UpdateMerchantStatusRequest, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResultVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateMerchantStatus(merchantId, updateMerchantStatusRequest, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminMerchantControllerApi.updateMerchantStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminMerchantControllerApi - factory interface
 */
export const AdminMerchantControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminMerchantControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {number} merchantId 
         * @param {AuditMerchantRequest} auditMerchantRequest 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        auditMerchant(merchantId: number, auditMerchantRequest: AuditMerchantRequest, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultVoid> {
            return localVarFp.auditMerchant(merchantId, auditMerchantRequest, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} merchantId 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMerchantDetail(merchantId: number, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultMerchantVO> {
            return localVarFp.getMerchantDetail(merchantId, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} merchantId 
         * @param {UpdateMerchantStatusRequest} updateMerchantStatusRequest 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateMerchantStatus(merchantId: number, updateMerchantStatusRequest: UpdateMerchantStatusRequest, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultVoid> {
            return localVarFp.updateMerchantStatus(merchantId, updateMerchantStatusRequest, authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminMerchantControllerApi - interface
 */
export interface AdminMerchantControllerApiInterface {
    /**
     * 
     * @param {number} merchantId 
     * @param {AuditMerchantRequest} auditMerchantRequest 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    auditMerchant(merchantId: number, auditMerchantRequest: AuditMerchantRequest, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultVoid>;

    /**
     * 
     * @param {number} merchantId 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getMerchantDetail(merchantId: number, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultMerchantVO>;

    /**
     * 
     * @param {number} merchantId 
     * @param {UpdateMerchantStatusRequest} updateMerchantStatusRequest 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateMerchantStatus(merchantId: number, updateMerchantStatusRequest: UpdateMerchantStatusRequest, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultVoid>;

}

/**
 * AdminMerchantControllerApi - object-oriented interface
 */
export class AdminMerchantControllerApi extends BaseAPI implements AdminMerchantControllerApiInterface {
    /**
     * 
     * @param {number} merchantId 
     * @param {AuditMerchantRequest} auditMerchantRequest 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public auditMerchant(merchantId: number, auditMerchantRequest: AuditMerchantRequest, authorization?: string, options?: RawAxiosRequestConfig) {
        return AdminMerchantControllerApiFp(this.configuration).auditMerchant(merchantId, auditMerchantRequest, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} merchantId 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMerchantDetail(merchantId: number, authorization?: string, options?: RawAxiosRequestConfig) {
        return AdminMerchantControllerApiFp(this.configuration).getMerchantDetail(merchantId, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} merchantId 
     * @param {UpdateMerchantStatusRequest} updateMerchantStatusRequest 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateMerchantStatus(merchantId: number, updateMerchantStatusRequest: UpdateMerchantStatusRequest, authorization?: string, options?: RawAxiosRequestConfig) {
        return AdminMerchantControllerApiFp(this.configuration).updateMerchantStatus(merchantId, updateMerchantStatusRequest, authorization, options).then((request) => request(this.axios, this.basePath));
    }
}

