/* tslint:disable */
/* eslint-disable */
/**
 * TheMall Admin API 文档
 * TheMall 商城管理系统 API 接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@themall.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CancelOrderRequest } from '../models';
// @ts-ignore
import type { CommonResultMerchantOrderListVO } from '../models';
// @ts-ignore
import type { CommonResultMerchantOrderVO } from '../models';
// @ts-ignore
import type { CommonResultOrderStatisticsVO } from '../models';
// @ts-ignore
import type { CommonResultVoid } from '../models';
/**
 * AdminOrderControllerApi - axios parameter creator
 */
export const AdminOrderControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} orderId 
         * @param {CancelOrderRequest} cancelOrderRequest 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelOrder: async (orderId: number, cancelOrderRequest: CancelOrderRequest, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orderId' is not null or undefined
            assertParamExists('cancelOrder', 'orderId', orderId)
            // verify required parameter 'cancelOrderRequest' is not null or undefined
            assertParamExists('cancelOrder', 'cancelOrderRequest', cancelOrderRequest)
            const localVarPath = `/api/admin/orders/{orderId}/cancel`
                .replace(`{${"orderId"}}`, encodeURIComponent(String(orderId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cancelOrderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} orderId 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrderDetail: async (orderId: number, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orderId' is not null or undefined
            assertParamExists('getOrderDetail', 'orderId', orderId)
            const localVarPath = `/api/admin/orders/{orderId}`
                .replace(`{${"orderId"}}`, encodeURIComponent(String(orderId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [shopId] 
         * @param {number} [merchantId] 
         * @param {number} [status] 
         * @param {string} [startTime] 
         * @param {string} [endTime] 
         * @param {string} [keyword] 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrderList: async (shopId?: number, merchantId?: number, status?: number, startTime?: string, endTime?: string, keyword?: string, page?: number, size?: number, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/orders`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (shopId !== undefined) {
                localVarQueryParameter['shopId'] = shopId;
            }

            if (merchantId !== undefined) {
                localVarQueryParameter['merchantId'] = merchantId;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (startTime !== undefined) {
                localVarQueryParameter['startTime'] = (startTime as any instanceof Date) ?
                    (startTime as any).toISOString() :
                    startTime;
            }

            if (endTime !== undefined) {
                localVarQueryParameter['endTime'] = (endTime as any instanceof Date) ?
                    (endTime as any).toISOString() :
                    endTime;
            }

            if (keyword !== undefined) {
                localVarQueryParameter['keyword'] = keyword;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [shopId] 
         * @param {number} [merchantId] 
         * @param {string} [startTime] 
         * @param {string} [endTime] 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrderStatistics: async (shopId?: number, merchantId?: number, startTime?: string, endTime?: string, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/orders/statistics`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (shopId !== undefined) {
                localVarQueryParameter['shopId'] = shopId;
            }

            if (merchantId !== undefined) {
                localVarQueryParameter['merchantId'] = merchantId;
            }

            if (startTime !== undefined) {
                localVarQueryParameter['startTime'] = (startTime as any instanceof Date) ?
                    (startTime as any).toISOString() :
                    startTime;
            }

            if (endTime !== undefined) {
                localVarQueryParameter['endTime'] = (endTime as any instanceof Date) ?
                    (endTime as any).toISOString() :
                    endTime;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminOrderControllerApi - functional programming interface
 */
export const AdminOrderControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminOrderControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} orderId 
         * @param {CancelOrderRequest} cancelOrderRequest 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelOrder(orderId: number, cancelOrderRequest: CancelOrderRequest, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResultVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelOrder(orderId, cancelOrderRequest, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminOrderControllerApi.cancelOrder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} orderId 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrderDetail(orderId: number, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResultMerchantOrderVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOrderDetail(orderId, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminOrderControllerApi.getOrderDetail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [shopId] 
         * @param {number} [merchantId] 
         * @param {number} [status] 
         * @param {string} [startTime] 
         * @param {string} [endTime] 
         * @param {string} [keyword] 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrderList(shopId?: number, merchantId?: number, status?: number, startTime?: string, endTime?: string, keyword?: string, page?: number, size?: number, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResultMerchantOrderListVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOrderList(shopId, merchantId, status, startTime, endTime, keyword, page, size, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminOrderControllerApi.getOrderList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [shopId] 
         * @param {number} [merchantId] 
         * @param {string} [startTime] 
         * @param {string} [endTime] 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrderStatistics(shopId?: number, merchantId?: number, startTime?: string, endTime?: string, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResultOrderStatisticsVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOrderStatistics(shopId, merchantId, startTime, endTime, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminOrderControllerApi.getOrderStatistics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminOrderControllerApi - factory interface
 */
export const AdminOrderControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminOrderControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {number} orderId 
         * @param {CancelOrderRequest} cancelOrderRequest 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelOrder(orderId: number, cancelOrderRequest: CancelOrderRequest, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultVoid> {
            return localVarFp.cancelOrder(orderId, cancelOrderRequest, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} orderId 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrderDetail(orderId: number, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultMerchantOrderVO> {
            return localVarFp.getOrderDetail(orderId, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} [shopId] 
         * @param {number} [merchantId] 
         * @param {number} [status] 
         * @param {string} [startTime] 
         * @param {string} [endTime] 
         * @param {string} [keyword] 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrderList(shopId?: number, merchantId?: number, status?: number, startTime?: string, endTime?: string, keyword?: string, page?: number, size?: number, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultMerchantOrderListVO> {
            return localVarFp.getOrderList(shopId, merchantId, status, startTime, endTime, keyword, page, size, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} [shopId] 
         * @param {number} [merchantId] 
         * @param {string} [startTime] 
         * @param {string} [endTime] 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrderStatistics(shopId?: number, merchantId?: number, startTime?: string, endTime?: string, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultOrderStatisticsVO> {
            return localVarFp.getOrderStatistics(shopId, merchantId, startTime, endTime, authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminOrderControllerApi - interface
 */
export interface AdminOrderControllerApiInterface {
    /**
     * 
     * @param {number} orderId 
     * @param {CancelOrderRequest} cancelOrderRequest 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    cancelOrder(orderId: number, cancelOrderRequest: CancelOrderRequest, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultVoid>;

    /**
     * 
     * @param {number} orderId 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getOrderDetail(orderId: number, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultMerchantOrderVO>;

    /**
     * 
     * @param {number} [shopId] 
     * @param {number} [merchantId] 
     * @param {number} [status] 
     * @param {string} [startTime] 
     * @param {string} [endTime] 
     * @param {string} [keyword] 
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getOrderList(shopId?: number, merchantId?: number, status?: number, startTime?: string, endTime?: string, keyword?: string, page?: number, size?: number, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultMerchantOrderListVO>;

    /**
     * 
     * @param {number} [shopId] 
     * @param {number} [merchantId] 
     * @param {string} [startTime] 
     * @param {string} [endTime] 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getOrderStatistics(shopId?: number, merchantId?: number, startTime?: string, endTime?: string, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultOrderStatisticsVO>;

}

/**
 * AdminOrderControllerApi - object-oriented interface
 */
export class AdminOrderControllerApi extends BaseAPI implements AdminOrderControllerApiInterface {
    /**
     * 
     * @param {number} orderId 
     * @param {CancelOrderRequest} cancelOrderRequest 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cancelOrder(orderId: number, cancelOrderRequest: CancelOrderRequest, authorization?: string, options?: RawAxiosRequestConfig) {
        return AdminOrderControllerApiFp(this.configuration).cancelOrder(orderId, cancelOrderRequest, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} orderId 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getOrderDetail(orderId: number, authorization?: string, options?: RawAxiosRequestConfig) {
        return AdminOrderControllerApiFp(this.configuration).getOrderDetail(orderId, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} [shopId] 
     * @param {number} [merchantId] 
     * @param {number} [status] 
     * @param {string} [startTime] 
     * @param {string} [endTime] 
     * @param {string} [keyword] 
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getOrderList(shopId?: number, merchantId?: number, status?: number, startTime?: string, endTime?: string, keyword?: string, page?: number, size?: number, authorization?: string, options?: RawAxiosRequestConfig) {
        return AdminOrderControllerApiFp(this.configuration).getOrderList(shopId, merchantId, status, startTime, endTime, keyword, page, size, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} [shopId] 
     * @param {number} [merchantId] 
     * @param {string} [startTime] 
     * @param {string} [endTime] 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getOrderStatistics(shopId?: number, merchantId?: number, startTime?: string, endTime?: string, authorization?: string, options?: RawAxiosRequestConfig) {
        return AdminOrderControllerApiFp(this.configuration).getOrderStatistics(shopId, merchantId, startTime, endTime, authorization, options).then((request) => request(this.axios, this.basePath));
    }
}

