/* tslint:disable */
/* eslint-disable */
/**
 * TheMall Admin API 文档
 * TheMall 商城管理系统 API 接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@themall.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CommonResultShopListVO } from '../models';
// @ts-ignore
import type { CommonResultVoid } from '../models';
/**
 * AdminShopControllerApi - axios parameter creator
 */
export const AdminShopControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} [status] 
         * @param {string} [keyword] 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getShopList: async (status?: number, keyword?: string, page?: number, size?: number, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/shops`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (keyword !== undefined) {
                localVarQueryParameter['keyword'] = keyword;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} shopId 
         * @param {number} status 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateShopStatus: async (shopId: number, status: number, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'shopId' is not null or undefined
            assertParamExists('updateShopStatus', 'shopId', shopId)
            // verify required parameter 'status' is not null or undefined
            assertParamExists('updateShopStatus', 'status', status)
            const localVarPath = `/api/admin/shops/{shopId}/status`
                .replace(`{${"shopId"}}`, encodeURIComponent(String(shopId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminShopControllerApi - functional programming interface
 */
export const AdminShopControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminShopControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} [status] 
         * @param {string} [keyword] 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getShopList(status?: number, keyword?: string, page?: number, size?: number, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResultShopListVO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getShopList(status, keyword, page, size, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminShopControllerApi.getShopList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} shopId 
         * @param {number} status 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateShopStatus(shopId: number, status: number, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResultVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateShopStatus(shopId, status, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminShopControllerApi.updateShopStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminShopControllerApi - factory interface
 */
export const AdminShopControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminShopControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {number} [status] 
         * @param {string} [keyword] 
         * @param {number} [page] 
         * @param {number} [size] 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getShopList(status?: number, keyword?: string, page?: number, size?: number, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultShopListVO> {
            return localVarFp.getShopList(status, keyword, page, size, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} shopId 
         * @param {number} status 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateShopStatus(shopId: number, status: number, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultVoid> {
            return localVarFp.updateShopStatus(shopId, status, authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminShopControllerApi - interface
 */
export interface AdminShopControllerApiInterface {
    /**
     * 
     * @param {number} [status] 
     * @param {string} [keyword] 
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getShopList(status?: number, keyword?: string, page?: number, size?: number, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultShopListVO>;

    /**
     * 
     * @param {number} shopId 
     * @param {number} status 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateShopStatus(shopId: number, status: number, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultVoid>;

}

/**
 * AdminShopControllerApi - object-oriented interface
 */
export class AdminShopControllerApi extends BaseAPI implements AdminShopControllerApiInterface {
    /**
     * 
     * @param {number} [status] 
     * @param {string} [keyword] 
     * @param {number} [page] 
     * @param {number} [size] 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getShopList(status?: number, keyword?: string, page?: number, size?: number, authorization?: string, options?: RawAxiosRequestConfig) {
        return AdminShopControllerApiFp(this.configuration).getShopList(status, keyword, page, size, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} shopId 
     * @param {number} status 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateShopStatus(shopId: number, status: number, authorization?: string, options?: RawAxiosRequestConfig) {
        return AdminShopControllerApiFp(this.configuration).updateShopStatus(shopId, status, authorization, options).then((request) => request(this.axios, this.basePath));
    }
}

