/* tslint:disable */
/* eslint-disable */
/**
 * TheMall Admin API 文档
 * TheMall 商城管理系统 API 接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@themall.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CommonResultVoid } from '../models';
/**
 * AdminProductControllerApi - axios parameter creator
 */
export const AdminProductControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} productId 
         * @param {number} status 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProductStatus: async (productId: number, status: number, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('updateProductStatus', 'productId', productId)
            // verify required parameter 'status' is not null or undefined
            assertParamExists('updateProductStatus', 'status', status)
            const localVarPath = `/api/admin/products/{productId}/status`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminProductControllerApi - functional programming interface
 */
export const AdminProductControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminProductControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} productId 
         * @param {number} status 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateProductStatus(productId: number, status: number, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResultVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateProductStatus(productId, status, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminProductControllerApi.updateProductStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminProductControllerApi - factory interface
 */
export const AdminProductControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminProductControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {number} productId 
         * @param {number} status 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProductStatus(productId: number, status: number, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultVoid> {
            return localVarFp.updateProductStatus(productId, status, authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminProductControllerApi - interface
 */
export interface AdminProductControllerApiInterface {
    /**
     * 
     * @param {number} productId 
     * @param {number} status 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateProductStatus(productId: number, status: number, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultVoid>;

}

/**
 * AdminProductControllerApi - object-oriented interface
 */
export class AdminProductControllerApi extends BaseAPI implements AdminProductControllerApiInterface {
    /**
     * 
     * @param {number} productId 
     * @param {number} status 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateProductStatus(productId: number, status: number, authorization?: string, options?: RawAxiosRequestConfig) {
        return AdminProductControllerApiFp(this.configuration).updateProductStatus(productId, status, authorization, options).then((request) => request(this.axios, this.basePath));
    }
}

