/* tslint:disable */
/* eslint-disable */
/**
 * TheMall Admin API 文档
 * TheMall 商城管理系统 API 接口文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@themall.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CodeLoginRequest } from '../models';
// @ts-ignore
import type { CommonResultLoginResult } from '../models';
// @ts-ignore
import type { CommonResultString } from '../models';
// @ts-ignore
import type { LoginRequest } from '../models';
// @ts-ignore
import type { VerificationCodeRequest } from '../models';
/**
 * AdminAuthControllerApi - axios parameter creator
 */
export const AdminAuthControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (loginRequest: LoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginRequest' is not null or undefined
            assertParamExists('login', 'loginRequest', loginRequest)
            const localVarPath = `/api/admin/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CodeLoginRequest} codeLoginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginByCode: async (codeLoginRequest: CodeLoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'codeLoginRequest' is not null or undefined
            assertParamExists('loginByCode', 'codeLoginRequest', codeLoginRequest)
            const localVarPath = `/api/admin/auth/login-by-code`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(codeLoginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {VerificationCodeRequest} verificationCodeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendLoginCode: async (verificationCodeRequest: VerificationCodeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'verificationCodeRequest' is not null or undefined
            assertParamExists('sendLoginCode', 'verificationCodeRequest', verificationCodeRequest)
            const localVarPath = `/api/admin/auth/send-login-code`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(verificationCodeRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {VerificationCodeRequest} verificationCodeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendVerificationCode: async (verificationCodeRequest: VerificationCodeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'verificationCodeRequest' is not null or undefined
            assertParamExists('sendVerificationCode', 'verificationCodeRequest', verificationCodeRequest)
            const localVarPath = `/api/admin/auth/send-code`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(verificationCodeRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminAuthControllerApi - functional programming interface
 */
export const AdminAuthControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminAuthControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResultLoginResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(loginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAuthControllerApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CodeLoginRequest} codeLoginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loginByCode(codeLoginRequest: CodeLoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResultLoginResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loginByCode(codeLoginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAuthControllerApi.loginByCode']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {VerificationCodeRequest} verificationCodeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendLoginCode(verificationCodeRequest: VerificationCodeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResultString>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendLoginCode(verificationCodeRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAuthControllerApi.sendLoginCode']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {VerificationCodeRequest} verificationCodeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendVerificationCode(verificationCodeRequest: VerificationCodeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResultString>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendVerificationCode(verificationCodeRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminAuthControllerApi.sendVerificationCode']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminAuthControllerApi - factory interface
 */
export const AdminAuthControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminAuthControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultLoginResult> {
            return localVarFp.login(loginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CodeLoginRequest} codeLoginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loginByCode(codeLoginRequest: CodeLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultLoginResult> {
            return localVarFp.loginByCode(codeLoginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {VerificationCodeRequest} verificationCodeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendLoginCode(verificationCodeRequest: VerificationCodeRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultString> {
            return localVarFp.sendLoginCode(verificationCodeRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {VerificationCodeRequest} verificationCodeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendVerificationCode(verificationCodeRequest: VerificationCodeRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultString> {
            return localVarFp.sendVerificationCode(verificationCodeRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminAuthControllerApi - interface
 */
export interface AdminAuthControllerApiInterface {
    /**
     * 
     * @param {LoginRequest} loginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultLoginResult>;

    /**
     * 
     * @param {CodeLoginRequest} codeLoginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    loginByCode(codeLoginRequest: CodeLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultLoginResult>;

    /**
     * 
     * @param {VerificationCodeRequest} verificationCodeRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sendLoginCode(verificationCodeRequest: VerificationCodeRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultString>;

    /**
     * 
     * @param {VerificationCodeRequest} verificationCodeRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sendVerificationCode(verificationCodeRequest: VerificationCodeRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommonResultString>;

}

/**
 * AdminAuthControllerApi - object-oriented interface
 */
export class AdminAuthControllerApi extends BaseAPI implements AdminAuthControllerApiInterface {
    /**
     * 
     * @param {LoginRequest} loginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig) {
        return AdminAuthControllerApiFp(this.configuration).login(loginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CodeLoginRequest} codeLoginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public loginByCode(codeLoginRequest: CodeLoginRequest, options?: RawAxiosRequestConfig) {
        return AdminAuthControllerApiFp(this.configuration).loginByCode(codeLoginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {VerificationCodeRequest} verificationCodeRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sendLoginCode(verificationCodeRequest: VerificationCodeRequest, options?: RawAxiosRequestConfig) {
        return AdminAuthControllerApiFp(this.configuration).sendLoginCode(verificationCodeRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {VerificationCodeRequest} verificationCodeRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sendVerificationCode(verificationCodeRequest: VerificationCodeRequest, options?: RawAxiosRequestConfig) {
        return AdminAuthControllerApiFp(this.configuration).sendVerificationCode(verificationCodeRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

